name: Julia CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-and-coverage:
    name: Julia 1.9 - Run Tests and Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Julia 1.9
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
          arch: x64

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Generate coverage data
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
